// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dead_letter_events.sql

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BulkInsertDeadLetterEventsParams struct {
	ID          pgtype.UUID
	RawData     []byte
	ErrorReason string
}
