// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dead_letter_events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertDeadLetter = `-- name: InsertDeadLetter :one
INSERT INTO dead_letter_events (id, raw_data, error_reason)
VALUES ($1, $2, $3)
returning id
`

type InsertDeadLetterParams struct {
	ID          pgtype.UUID
	RawData     []byte
	ErrorReason string
}

func (q *Queries) InsertDeadLetter(ctx context.Context, arg InsertDeadLetterParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertDeadLetter, arg.ID, arg.RawData, arg.ErrorReason)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
