// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BulkInsertEventsParams struct {
	ID           pgtype.UUID
	RawData      []byte
	EnrichedData []byte
}
