// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DeadLetterEvent struct {
	ID          pgtype.UUID
	RawData     []byte
	ErrorReason string
	FailedAt    pgtype.Timestamptz
}

type Event struct {
	ID           pgtype.UUID
	RawData      []byte
	EnrichedData []byte
	CreatedAt    pgtype.Timestamptz
}
